<?php
require_once '../config/init.php';

$kategori = isset($_GET['kategori']) ? $_GET['kategori'] : '';

$query = "SELECT produk.*, profil_usaha.nama_usaha 
          FROM produk 
          JOIN profil_usaha ON produk.id_profil = profil_usaha.id_profil";

if (!empty($kategori)) {
    $query .= " WHERE produk.id_kategori = ?";
    $stmt = $conn->prepare($query);
    $stmt->bind_param("s", $kategori);
} else {
    $stmt = $conn->prepare($query);
}

$stmt->execute();
$result = $stmt->get_result();
?>


<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoUMKM</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="../css/kategori.css">
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="nav-left" >
            <a href="../pages/beranda.php">
                <img src="../assets/img/image (2).png" alt="logo umkm" class="logo-umkm" >
            </a>     
        </div>
        
        <div class="search-container">
            <div class="dropdown-container">
                <div class="product_category" id="categorySelect">
                    <span id="categoryText">Kategori</span>
                </div>
                <div class="dropdown-menu" id="dropdownMenu">
                    <div class="dropdown-item <?= $kategori == '' ? 'active' : '' ?>" data-value="">Semua Kategori</div>
                    <div class="dropdown-item <?= $kategori == 'makanan-minuman' ? 'active' : '' ?>" data-value="makanan-minuman">Makanan dan Minuman</div>
                    <div class="dropdown-item <?= $kategori == 'fashion' ? 'active' : '' ?>" data-value="fashion">Fashion</div>
                    <div class="dropdown-item <?= $kategori == 'kerajinan' ? 'active' : '' ?>" data-value="kerajinan">Kerajinan</div>
                    <div class="dropdown-item <?= $kategori == 'kecantikan' ? 'active' : '' ?>" data-value="kecantikan">Produk Kecantikan</div>
                    <div class="dropdown-item <?= $kategori == 'pertanian' ? 'active' : '' ?>" data-value="pertanian">Pertanian dan Perkebunan</div>
                </div>
            </div>
            <input type="text" class="search-input" placeholder="nama produk" id="searchInput">
            <button class="search-btn" id="searchBtn">Search</button>
        </div>
        
        <div class="header-buttons">
            <a href="#" class="btn">Masuk</a>
            <a href="#" class="btn btn-primary">Daftar</a>
        </div>
    </header>

    <!-- Categories Section -->
    <section class="categories">
        <button class="product-category" data-category="">Semua</button>
        <button class="product-category" data-category="makanan-minuman">Makanan dan Minuman</button>
        <button class="product-category" data-category="fashion">Fashion</button>
        <button class="product-category" data-category="kerajinan">Kerajinan</button>
        <button class="product-category" data-category="kecantikan">Produk Kecantikan</button>
        <button class="product-category" data-category="pertanian">Pertanian dan Perkebunan</button>
    </section>

    <!-- Main Content -->
    <div class="container">
        <div class="products-grid" id="productsGrid">
            <!-- Products will be generated by JavaScript -->
        </div>
    </div>

    <script>
        $(document).ready(function() {
            // Sample product data dengan kategori yang sesuai
            const products = [
                { title: "Nasi Gudeg", subtitle: "Warung Bu Sari", price: "Rp. 15.000", category: "makanan-minuman" },
                { title: "Es Teh Manis", subtitle: "Depot Segar", price: "Rp. 5.000", category: "makanan-minuman" },
                { title: "Kemeja Batik", subtitle: "Batik Nusantara", price: "Rp. 150.000", category: "fashion" },
                { title: "Sepatu Sneakers", subtitle: "Toko Sepatu Jaya", price: "Rp. 200.000", category: "fashion" },
                { title: "Tas Anyaman", subtitle: "Kerajinan Desa", price: "Rp. 75.000", category: "kerajinan" },
                { title: "Patung Kayu", subtitle: "Art & Craft", price: "Rp. 100.000", category: "kerajinan" },
                { title: "Serum Wajah", subtitle: "Beauty Shop", price: "Rp. 85.000", category: "kecantikan" },
                { title: "Lipstik Natural", subtitle: "Kosmetik Alami", price: "Rp. 45.000", category: "kecantikan" },
                { title: "Beras Organik", subtitle: "Tani Sejahtera", price: "Rp. 25.000", category: "pertanian" },
                { title: "Kopi Arabika", subtitle: "Kebun Kopi", price: "Rp. 50.000", category: "pertanian" },
                { title: "Soto Ayam", subtitle: "Warung Pak Mahmud", price: "Rp. 18.000", category: "makanan-minuman" },
                { title: "Jus Jeruk", subtitle: "Fresh Juice", price: "Rp. 12.000", category: "makanan-minuman" },
                { title: "Dress Casual", subtitle: "Fashion Store", price: "Rp. 125.000", category: "fashion" },
                { title: "Topi Rajut", subtitle: "Handmade Shop", price: "Rp. 35.000", category: "fashion" },
                { title: "Gelang Manik", subtitle: "Craft Corner", price: "Rp. 25.000", category: "kerajinan" },
                { title: "Dompet Kulit", subtitle: "Leather Works", price: "Rp. 65.000", category: "kerajinan" },
                { title: "Sabun Herbal", subtitle: "Natural Care", price: "Rp. 15.000", category: "kecantikan" },
                { title: "Masker Wajah", subtitle: "Skincare Plus", price: "Rp. 30.000", category: "kecantikan" }
            ];

            let currentCategory = '';
            let currentCategoryText = 'Kategori';

            // Custom dropdown functionality
            $('#categorySelect').click(function(e) {
                e.stopPropagation();
                $('#dropdownMenu').toggle();
            });

            // Dropdown item click
            $('.dropdown-item').click(function() {
                const value = $(this).data('value');
                const text = $(this).text();
                
                currentCategory = value;
                currentCategoryText = text;
                
                $('#categoryText').text(text);
                $('#dropdownMenu').hide();
                
                // Update category buttons to match
                $('.categories .product-category').removeClass('active');
                $('.categories .product-category[data-category="' + currentCategory + '"]').addClass('active');
                
                filterProducts();
            });

            // Close dropdown when clicking outside
            $(document).click(function() {
                $('#dropdownMenu').hide();
            });

            // Search and filter functionality
            function filterProducts() {
                const searchTerm = $('#searchInput').val().toLowerCase();
                const selectedCategory = currentCategory;
                
                let filteredProducts = products;
                
                // Filter by category
                if (selectedCategory) {
                    filteredProducts = filteredProducts.filter(product => 
                        product.category === selectedCategory
                    );
                }
                
                // Filter by search term
                if (searchTerm) {
                    filteredProducts = filteredProducts.filter(product => 
                        product.title.toLowerCase().includes(searchTerm) || 
                        product.subtitle.toLowerCase().includes(searchTerm)
                    );
                }
                
                generateProducts(filteredProducts);
            }

            // Generate product cards
            function generateProducts(filteredProducts = products) {
                const grid = $('#productsGrid');
                grid.empty();
                
                filteredProducts.forEach(function(product, index) {
                    const productCard = `
                        <div class="product-card" data-index="${index}">
                            <div class="product-image">
                                📷
                            </div>
                            <div class="product-info">
                                <div class="product-title">${product.title}</div>
                                <div class="product-subtitle">${product.subtitle}</div>
                                <div class="product-price">${product.price}</div>
                            </div>
                        </div>
                    `;
                    grid.append(productCard);
                });
            }

            // Category button click (dari section categories)
            $('.categories .product-category').click(function() {
                // Remove active class from all buttons
                $('.categories .product-category').removeClass('active');
                
                // Add active class to clicked button
                $(this).addClass('active');
                
                // Get category from data attribute
                currentCategory = $(this).data('category');
                
                // Update dropdown text to match
                const categoryMap = {
                    '': 'Kategori',
                    'makanan-minuman': 'Makanan dan Minuman',
                    'fashion': 'Fashion',
                    'kerajinan': 'Kerajinan',
                    'kecantikan': 'Produk Kecantikan',
                    'pertanian': 'Pertanian dan Perkebunan'
                };
                
                currentCategoryText = categoryMap[currentCategory];
                $('#categoryText').text(currentCategoryText);
                
                // Filter products
                filterProducts();
            });

            // Search button click
            $('#searchBtn').click(function() {
                filterProducts();
            });

            // Category dropdown change - remove this since we're using custom dropdown
            // $('#categorySelect').change(function() {
            //     currentCategory = $(this).val();
            //     
            //     // Update category buttons to match
            //     $('.categories .product-category').removeClass('active');
            //     $('.categories .product-category[data-category="' + currentCategory + '"]').addClass('active');
            //     
            //     filterProducts();
            // });

            // Search on Enter key
            $('#searchInput').keypress(function(e) {
                if (e.which == 13) {
                    filterProducts();
                }
            });

            // Product card click event
            $(document).on('click', '.product-card', function() {
                const index = $(this).data('index');
                const filteredProducts = products.filter(product => {
                    const searchTerm = $('#searchInput').val().toLowerCase();
                    const selectedCategory = currentCategory || $('#categorySelect').val();
                    
                    let matches = true;
                    
                    if (selectedCategory) {
                        matches = matches && product.category === selectedCategory;
                    }
                    
                    if (searchTerm) {
                        matches = matches && (product.title.toLowerCase().includes(searchTerm) || 
                                           product.subtitle.toLowerCase().includes(searchTerm));
                    }
                    
                    return matches;
                });
                
                alert('Produk diklik: ' + filteredProducts[index].title);
            });

            // Add hover effects with jQuery
            $(document).on('mouseenter', '.product-card', function() {
                $(this).css('cursor', 'pointer');
            });

            // Initialize - set "Semua" as active and show all products
            $('.categories .product-category[data-category=""]').addClass('active');
            generateProducts();
        });
    </script>

    <?php include '../Includes/footer.php'; ?>
</body>
</html>