<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoUMKM</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="../css/kategori.css">

</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="logo">
            <div class="logo-icon">🏪</div>
            GoUMKM
        </div>
        
        <div class="search-container">
            <select class="category-select" id="categorySelect">
                <option value="">Kategori</option>
            </select>
            <input type="text" class="search-input" placeholder="nama produk" id="searchInput">
            <button class="search-btn" id="searchBtn">Search</button>
        </div>
        
        <div class="header-buttons">
            <a href="#" class="btn">Masuk</a>
            <a href="#" class="btn btn-primary">Daftar</a>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="products-grid" id="productsGrid">
            <!-- Products will be generated by JavaScript -->
        </div>
    </div>

    <script>
        $(document).ready(function() {
            // Sample product data
            const products = [
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "elektronik" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "elektronik" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "fashion" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "fashion" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "makanan" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "makanan" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "kesehatan" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "kesehatan" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "rumah" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "rumah" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "otomotif" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "otomotif" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "olahraga" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "olahraga" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "buku" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "buku" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "elektronik" },
                { title: "Nama Produk", subtitle: "Nama Toko", price: "Rp. -", category: "fashion" }
            ];

            // Generate product cards
            function generateProducts(filteredProducts = products) {
                const grid = $('#productsGrid');
                grid.empty();
                
                filteredProducts.forEach(function(product, index) {
                    const productCard = `
                        <div class="product-card" data-index="${index}">
                            <div class="product-image">
                                📷
                            </div>
                            <div class="product-info">
                                <div class="product-title">${product.title}</div>
                                <div class="product-subtitle">${product.subtitle}</div>
                                <div class="product-price">${product.price}</div>
                            </div>
                        </div>
                    `;
                    grid.append(productCard);
                });
            }

            // Search and filter functionality
            function filterProducts() {
                const searchTerm = $('#searchInput').val().toLowerCase();
                const selectedCategory = $('#categorySelect').val();
                
                let filteredProducts = products;
                
                // Filter by category
                if (selectedCategory) {
                    filteredProducts = filteredProducts.filter(product => 
                        product.category === selectedCategory
                    );
                }
                
                // Filter by search term
                if (searchTerm) {
                    filteredProducts = filteredProducts.filter(product => 
                        product.title.toLowerCase().includes(searchTerm) || 
                        product.subtitle.toLowerCase().includes(searchTerm)
                    );
                }
                
                generateProducts(filteredProducts);
            }

            // Search button click
            $('#searchBtn').click(function() {
                filterProducts();
            });

            // Category change
            $('#categorySelect').change(function() {
                filterProducts();
            });

            // Search on Enter key
            $('#searchInput').keypress(function(e) {
                if (e.which == 13) {
                    filterProducts();
                }
            });

            // Product card click event
            $(document).on('click', '.product-card', function() {
                const index = $(this).data('index');
                alert('Produk diklik: ' + products[index].title);
            });

            // Add hover effects with jQuery
            $(document).on('mouseenter', '.product-card', function() {
                $(this).css('cursor', 'pointer');
            });

            // Initialize products
            generateProducts();
        });
    </script>
</body>
</html>